// utils/exportRoute.ts

export function buildGoogleMapsUrl(steps: any[]): string {
  if (steps.length === 0) return ''

  // Google Maps directions URL supports up to 10 waypoints
  const places = steps.slice(0, 10)

  // Origin = first stop
  const origin = `${places[0].place.latitude},${places[0].place.longitude}`

  // Destination = last stop  
  const destination = `${places[places.length - 1].place.latitude},${places[places.length - 1].place.longitude}`

  // Waypoints = everything in between
  const waypoints = places
    .slice(1, -1)
    .map((s: any) => `${s.place.latitude},${s.place.longitude}`)
    .join('|')

  const params = new URLSearchParams({
    api:         '1',
    origin,
    destination,
    travelmode:  'walking',
  })

  if (waypoints) {
    params.set('waypoints', waypoints)
  }

  return `https://www.google.com/maps/dir/?${params.toString()}`
}

// Also build individual place URLs for each stop
export function buildPlaceUrl(lat: number, lng: number, name: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}&query_place=${lat},${lng}`
}

export function buildAppleMapsUrl(steps: any[]): string {
  if (steps.length === 0) return ''

  const places = steps.slice(0, 10)

  // Apple Maps supports saddr (start), daddr (destinations)
  const stops = places
    .map((s: any) => `${s.place.latitude},${s.place.longitude}`)
    .join('+to:')

  return `http://maps.apple.com/?saddr=${stops}&dirflg=w`
}

export function generateGPX(steps: any[], title: string): string {
  const waypoints = steps.map((step: any) => `
  <wpt lat="${step.place.latitude}" lon="${step.place.longitude}">
    <name>${escapeXml(step.place.name)}</name>
    <desc>${escapeXml(step.time)} — ${escapeXml(step.type)} — €${step.estimatedSpend}</desc>
    <sym>City</sym>
  </wpt>`).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Barcelona Route"
  xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(title)}</name>
    <desc>Barcelona itinerary generated by barcelonaroute.com</desc>
    <time>${new Date().toISOString()}</time>
  </metadata>
${waypoints}
</gpx>`
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;')
}



export function generateKML(steps: any[], title: string): string {
    const placemarks = steps.map((step: any, i: number) => `
      <Placemark>
        <name>${escapeXml(`${i + 1}. ${step.place.name}`)}</name>
        <description>${escapeXml(
          `${step.time} · ${step.type}\n${step.description}\nEstimated: €${step.estimatedSpend}`
        )}</description>
        <Point>
          <coordinates>${step.place.longitude},${step.place.latitude},0</coordinates>
        </Point>
      </Placemark>`).join('\n')
  
    return `<?xml version="1.0" encoding="UTF-8"?>
  <kml xmlns="http://www.opengis.net/kml/2.2">
    <Document>
      <name>${escapeXml(title)}</name>
      <description>Barcelona itinerary from barcelonaroute.com</description>
      <Style id="stop-style">
        <IconStyle>
          <color>ff2d62c4</color>
          <Icon><href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href></Icon>
        </IconStyle>
      </Style>
  ${placemarks}
    </Document>
  </kml>`
  }